name: AWS EC2 CICD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: ["main"]

jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Copy Repository Code
        uses: actions/checkout@v4

      - name: Setup Node JS
        uses: actions/setup-node@v4
        with:
          version: 20.15

      - name: Check Installation
        run: node -v

      - name: Installation
        run: npm install

      - name: Building code
        run: npm run build

      - name: completed
        run: npm run test
